addons:
  apt:
    packages:
      - nvidia-common
      - nvidia-cuda-toolkit
      - nvidia-cuda-dev
      
      
env:
  global:
    - CXXFLAGS="-Wall -Wextra -Werror"
    - INSTALL_DIR=~/mylibs
    - NVML_FILE=cuda_346.46_gdk_linux.run
    - NVML_LINK=http://developer.download.nvidia.com/compute/cuda/7_0/Prod/local_installers/
  matrix:
    - USE_NVML=1 USE_SM=sm_10
    - USE_NVML=0 USE_SM=sm_20
    
    
    
before_install:

#   - sudo apt-get install -qq nvidia-cuda-toolkit
  - sudo apt-add-repository multiverse
  - sudo apt-get update -qq
  # nvcc 5.5: <= gcc 4.8
#  - sudo apt-get install -qq gcc-4.8 g++-4.8
#  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
  - gcc --version && g++ --version
  - sudo apt-get install -qq nvidia-cuda-toolkit
  - sudo apt-get install -qq nvidia-cuda-dev
  - nvcc --version
  - if [ $USE_NVML -eq 1 ]; then wget $NVML_LINK$NVML_FILE && chmod u+x $NVML_FILE && sudo ./$NVML_FILE --silent --installdir=/ ; fi
  - if [ $USE_NVML -eq 1 ]; then export CMAKE_PREFIX_PATH=/usr/src/gdk/nvml/lib/ ; fi
  - sudo find /usr/ -name nvml.h
  - sudo find /usr/ -name nppdefs.h  
  
#   - sudo apt-get install -qq nvidia-cuda-dev
#   - nvcc --version
#   - if [ $USE_NVML -eq 1 ]; then wget $NVML_LINK$NVML_FILE && chmod u+x $NVML_FILE && sudo ./$NVML_FILE --silent --installdir=/ ; fi
#   - if [ $USE_NVML -eq 1 ]; then export CMAKE_PREFIX_PATH=/usr/src/gdk/nvml/lib/ ; fi
#   - sudo find /usr/ -name libcuda*.so
#   - sudo find /usr/ -name nvml.h
#   - sudo find /usr/ -name libnvidia*.so
#   - sudo find /usr/ -name libnvml*.so

  
  
 
  - wget -O cmake.sh https://cmake.org/files/v3.14/cmake-3.14.1-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  - export PATH=/usr/local/bin:$PATH
  - cmake --version
script:
  - sh ./build.sh
  
  
