matrix:
  include:
    - name: CUDA 10
      env:
      - CUDA=10.2.89-1
      - CUDA_SHORT=10.2
      - UBUNTU_VERSION=ubuntu1804
      dist: focal

addons:
  apt:
    packages:
      - nvidia-common
      - nvidia-cuda-toolkit=10.1
      - nvidia-cuda-dev
      
      
before_install:

  - nvcc --version
  - sudo find /usr/ -name nppdefs.h

  
#   - sudo apt-get install -qq nvidia-cuda-dev
#   - nvcc --version
#   - if [ $USE_NVML -eq 1 ]; then wget $NVML_LINK$NVML_FILE && chmod u+x $NVML_FILE && sudo ./$NVML_FILE --silent --installdir=/ ; fi
#   - if [ $USE_NVML -eq 1 ]; then export CMAKE_PREFIX_PATH=/usr/src/gdk/nvml/lib/ ; fi
#   - sudo find /usr/ -name libcuda*.so
#   - sudo find /usr/ -name nvml.h
#   - sudo find /usr/ -name libnvidia*.so
#   - sudo find /usr/ -name libnvml*.so

  
  
 
  - wget -O cmake.sh https://cmake.org/files/v3.14/cmake-3.14.1-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
  - export PATH=/usr/local/bin:$PATH
  - cmake --version
script:
  - sh ./build.sh
  
  
